name: Integration Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['master']

jobs:
  integrate:
    runs-on: ubuntu-latest
    permissions:  # needed for "Publish Test Results" action
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java distribution
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add permissions for Gradle
        run: chmod +x gradlew

      - name: Assemble
        id: 'assemble'
        run: ./gradlew assembleDebug

      - name: Unit Tests
        id: unit_tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: true

      - name: Instrumented Tests
        id: instrumented_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: default
          emulator-boot-timeout: 900
          emulator-options: "-no-window -no-audio -no-snapshot -no-boot-anim -camera-back none -camera-front none -dns-server 8.8.8.8 -accel off"
          script: |
            echo "Listing devices before running tests (ARM64 emulator, software emulation -accel off):"
            adb devices
            echo "Running Gradle tests..."
            ./gradlew connectedDebugAndroidTest
        continue-on-error: true

      - name: Test Results Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/**/TEST-*.xml

      - name: Test Results Presentation
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        with:
          files: app/build/**/TEST-*.xml

      - name: Check for failures
        if: steps.unit_tests.outcome == 'failure' || steps.instrumented_tests.outcome == 'failure'
        run: exit 1